/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\dev\three-next\public\suzume.glb -o c:\dev\three-next\public\suzume.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Suzanne: THREE.Mesh
  }
  materials: {
    floor: THREE.MeshBasicMaterial
    suzume: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/suzume.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.floor} />
      <mesh geometry={nodes.Suzanne.geometry} material={materials.suzume} position={[0, 0.553, 0]} rotation={[-0.596, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/suzume.glb')
